apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry
  labels:
    app: tbyte-collector
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: tbyte-collector
  endpoints:
    - port: prometheus
      interval: 30s
      path: /metrics
      honorLabels: true
