apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tbyte-collector-collector
  endpoints:
  - port: prometheus
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - opentelemetry
