{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tbyte-microservices.fullname" . }}-backend
  labels:
    {{- include "tbyte-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if .Values.backend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.backend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tbyte-microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
