# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "tbyte-terragrunt-state-432801802107"
    encrypt      = true
    key          = "./terraform.tfstate"
    region       = "eu-central-1"
    use_lockfile = true
  }
}
