apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tbyte-microservices.fullname" . }}-backend
  labels:
    {{- include "tbyte-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchLabels:
      {{- include "tbyte-microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "tbyte-microservices.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: frontend
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 5432  # RDS PostgreSQL
    - protocol: TCP
      port: 443   # AWS APIs
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
