{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tbyte-microservices.fullname" . }}-backend
  labels:
    {{- include "tbyte-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.serviceAccount.roleArn }}
{{- end }}
