apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/tbyte.git
    targetRevision: main
    path: apps/karpenter
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
