apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/eks-gitops-lab.git
    targetRevision: main
    path: apps/promtail
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
