apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Before Vault
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/eks-gitops-lab.git
    targetRevision: main
    path: apps/secrets-store-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
