apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tbyte-microservices
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/tbyte
    targetRevision: HEAD
    path: apps/tbyte-microservices
  destination:
    server: https://kubernetes.default.svc
    namespace: tbyte
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
