apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # After vault (wave 1)
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/tbyte.git
    targetRevision: main
    path: apps/vault-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
