apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: tbyte
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        host: "{{ .host | split \":\" | first }}"
        port: "{{ .port | toString }}"
        dbname: "{{ .dbname }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
  - extract:
      key: eks-gitops-lab-postgres-password
