apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: tbyte
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
  - secretKey: host
    remoteRef:
      key: tbyte-dev-postgres-password
      property: host
  - secretKey: port
    remoteRef:
      key: tbyte-dev-postgres-password
      property: port
  - secretKey: dbname
    remoteRef:
      key: tbyte-dev-postgres-password
      property: dbname
  - secretKey: username
    remoteRef:
      key: tbyte-dev-postgres-password
      property: username
  - secretKey: password
    remoteRef:
      key: tbyte-dev-postgres-password
      property: password
