apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: tbyte
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DB_HOST: "{{ .host | toString }}"
        DB_USERNAME: "{{ .username | toString }}"
        DB_PASSWORD: "{{ .password | toString }}"
        DB_NAME: "{{ .dbname | toString }}"
        DB_PORT: "{{ .port | toString }}"
  dataFrom:
  - extract:
      key: eks-gitops-lab-postgres-password
