apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac-setup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chiju/eks-gitops-lab.git
    targetRevision: main
    path: apps/rbac-setup
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
