apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: demo
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-demo-secrets
  namespace: demo
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "demo-app"
    objects: |
      - objectName: "db_host"
        secretPath: "secret/data/demo/config"
        secretKey: "db_host"
      - objectName: "db_port"
        secretPath: "secret/data/demo/config"
        secretKey: "db_port"
      - objectName: "db_user"
        secretPath: "secret/data/demo/config"
        secretKey: "db_user"
      - objectName: "db_password"
        secretPath: "secret/data/demo/config"
        secretKey: "db_password"
      - objectName: "api_key"
        secretPath: "secret/data/demo/config"
        secretKey: "api_key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: demo-app
      containers:
      - name: app
        image: nginx:alpine
        volumeMounts:
        - name: secrets
          mountPath: /mnt/secrets
          readOnly: true
        command:
        - /bin/sh
        - -c
        - |
          echo "Demo app started with CSI driver!"
          echo "Secrets are in /mnt/secrets/"
          echo "---"
          ls -la /mnt/secrets/
          echo "---"
          echo "DB_HOST: $(cat /mnt/secrets/db_host)"
          echo "DB_PORT: $(cat /mnt/secrets/db_port)"
          echo "DB_USER: $(cat /mnt/secrets/db_user)"
          echo "DB_PASSWORD: $(cat /mnt/secrets/db_password)"
          echo "API_KEY: $(cat /mnt/secrets/api_key)"
          echo "---"
          echo "App running..."
          tail -f /dev/null
      volumes:
      - name: secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vault-demo-secrets"
