apiVersion: v2
name: karpenter
description: Karpenter node autoscaler
type: application
version: 1.0.0
appVersion: "1.8.2"
dependencies:
  - name: karpenter
    version: 1.8.2
    repository: oci://public.ecr.aws/karpenter
