apiVersion: v1
kind: ConfigMap
metadata:
  name: rollback-commands
  namespace: default
data:
  rollback.sh: |
    #!/bin/bash
    # Manual Rollback Commands for Production
    
    echo "🚨 ROLLBACK OPTIONS:"
    echo "1. Immediate Abort (stops canary, keeps stable)"
    echo "   kubectl argo rollouts abort frontend-rollout"
    echo ""
    echo "2. Rollback to Previous Version"
    echo "   kubectl argo rollouts undo frontend-rollout"
    echo ""
    echo "3. Rollback to Specific Revision"
    echo "   kubectl argo rollouts undo frontend-rollout --to-revision=N"
    echo ""
    echo "4. GitOps Rollback (Safest - Recommended)"
    echo "   git revert HEAD && git push origin main"
    echo ""
    echo "5. Check Rollout Status"
    echo "   kubectl argo rollouts get rollout frontend-rollout"
    echo ""
    echo "6. Watch Rollout Progress"
    echo "   kubectl argo rollouts get rollout frontend-rollout --watch"
    
  auto-rollback-thresholds.yaml: |
    # Automatic Rollback Thresholds (Production Standards)
    success_rate: ">= 95%"      # Netflix: 99%, Spotify: 95%
    latency_p95: "<= 500ms"     # Industry standard
    latency_p99: "<= 1000ms"    # Acceptable for web apps
    error_rate: "<= 1%"         # Maximum tolerable
    cpu_usage: "<= 80%"         # Resource efficiency
    memory_usage: "<= 100MB"    # Container limit
    
    # Failure Limits (How many failures before rollback)
    success_rate_failures: 3    # 3 consecutive failures
    latency_failures: 3         # 3 consecutive failures  
    error_rate_failures: 2      # 2 consecutive failures (strict)
    resource_failures: 3        # 3 consecutive failures
    
    # Analysis Intervals
    check_interval: "30s"       # Check every 30 seconds
    analysis_duration: "5m"     # Total analysis time per step
