apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tbyte-microservices.fullname" . }}-frontend
  labels:
    {{- include "tbyte-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  podSelector:
    matchLabels:
      {{- include "tbyte-microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "tbyte-microservices.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: backend
    ports:
    - protocol: TCP
      port: 3000
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
