{{- if and .Values.frontend.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tbyte-microservices.fullname" . }}-frontend
  labels:
    {{- include "tbyte-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "tbyte-microservices.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
