{{- if .Values.frontend.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "tbyte-microservices.fullname" . }}-frontend-vs
  labels:
    {{- include "tbyte-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  hosts:
  - {{ include "tbyte-microservices.fullname" . }}-frontend
  http:
  - route:
    - destination:
        host: {{ include "tbyte-microservices.fullname" . }}-frontend
      weight: 100
    - destination:
        host: {{ include "tbyte-microservices.fullname" . }}-frontend-canary
      weight: 0
{{- end }}
