apiVersion: v2
name: istio-base
description: Istio Base CRDs
type: application
version: 0.1.0
appVersion: "1.28.1"

dependencies:
- name: base
  version: 1.28.1
  repository: https://istio-release.storage.googleapis.com/charts
