apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: tbyte-dev-node-group-role
  amiSelectorTerms:
    - alias: al2023@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: tbyte-dev
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: tbyte-dev
