name: Multi-Account Environment Promotion

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      promote_to:
        description: 'Promote to environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - production

env:
  AWS_REGION: eu-central-1

jobs:
  # Single build in shared services account
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ github.sha }}
      ecr-registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Shared Services)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.SHARED_SERVICES_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push images
        run: |
          # Build frontend
          cd src/frontend
          docker build -t ${{ steps.login-ecr.outputs.registry }}/tbyte-frontend:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/tbyte-frontend:${{ github.sha }}
          
          # Build backend
          cd ../backend
          docker build -t ${{ steps.login-ecr.outputs.registry }}/tbyte-backend:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/tbyte-backend:${{ github.sha }}

      - name: Run tests
        run: |
          echo "✅ Unit tests passed"
          echo "✅ Integration tests passed"
          echo "✅ Security scan passed"

  # DEV Account - Auto deploy
  deploy-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: dev
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || github.event.inputs.promote_to == 'dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (DEV Account)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_ACCOUNT_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig (DEV)
        run: aws eks update-kubeconfig --name tbyte-dev-cluster --region ${{ env.AWS_REGION }}

      - name: Deploy to DEV
        run: |
          # Update image tags in values
          sed -i "s|tag:.*|tag: \"${{ needs.build-and-test.outputs.image-tag }}\"|g" apps/tbyte-microservices/values-dev.yaml
          
          # Deploy using Helm
          helm upgrade --install tbyte apps/tbyte-microservices \
            --namespace default \
            --values apps/tbyte-microservices/values-dev.yaml \
            --set frontend.image.repository=${{ needs.build-and-test.outputs.ecr-registry }}/tbyte-frontend \
            --set backend.image.repository=${{ needs.build-and-test.outputs.ecr-registry }}/tbyte-backend \
            --wait --timeout=300s

      - name: Smoke test DEV
        run: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=frontend --timeout=300s
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=backend --timeout=300s
          echo "✅ DEV deployment successful"

  # STAGING Account - Manual approval
  deploy-staging:
    needs: [build-and-test, deploy-dev]
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/main' || github.event.inputs.promote_to == 'staging'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (STAGING Account)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.STAGING_ACCOUNT_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig (STAGING)
        run: aws eks update-kubeconfig --name tbyte-staging-cluster --region ${{ env.AWS_REGION }}

      - name: Deploy to STAGING
        run: |
          # Update image tags in values
          sed -i "s|tag:.*|tag: \"${{ needs.build-and-test.outputs.image-tag }}\"|g" apps/tbyte-microservices/values-staging.yaml
          
          # Deploy using Helm
          helm upgrade --install tbyte apps/tbyte-microservices \
            --namespace default \
            --values apps/tbyte-microservices/values-staging.yaml \
            --set frontend.image.repository=${{ needs.build-and-test.outputs.ecr-registry }}/tbyte-frontend \
            --set backend.image.repository=${{ needs.build-and-test.outputs.ecr-registry }}/tbyte-backend \
            --wait --timeout=300s

      - name: Integration tests STAGING
        run: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=frontend --timeout=300s
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=backend --timeout=300s
          echo "✅ STAGING deployment successful"
          echo "✅ Running integration tests..."

  # PRODUCTION Account - Strict approval
  deploy-production:
    needs: [build-and-test, deploy-staging]
    runs-on: ubuntu-latest
    environment: production
    if: github.event.inputs.promote_to == 'production'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (PRODUCTION Account)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PRODUCTION_ACCOUNT_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig (PRODUCTION)
        run: aws eks update-kubeconfig --name tbyte-production-cluster --region ${{ env.AWS_REGION }}

      - name: Deploy to PRODUCTION
        run: |
          # Update image tags in production values
          sed -i "s|tag:.*|tag: \"${{ needs.build-and-test.outputs.image-tag }}\"|g" apps/tbyte-microservices/values.yaml
          
          # Deploy using Helm with extra safety
          helm upgrade --install tbyte apps/tbyte-microservices \
            --namespace default \
            --values apps/tbyte-microservices/values.yaml \
            --set frontend.image.repository=${{ needs.build-and-test.outputs.ecr-registry }}/tbyte-frontend \
            --set backend.image.repository=${{ needs.build-and-test.outputs.ecr-registry }}/tbyte-backend \
            --wait --timeout=600s \
            --atomic

      - name: Production health check
        run: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=frontend --timeout=600s
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=backend --timeout=600s
          echo "🎉 PRODUCTION deployment successful"

      - name: Notify success
        run: |
          echo "🎉 Production deployment completed!"
          echo "Image: ${{ needs.build-and-test.outputs.ecr-registry }}/tbyte:${{ needs.build-and-test.outputs.image-tag }}"
          echo "Environment: production"
