name: Terragrunt Infrastructure

on:
  push:
    branches: [main, feature/*]
    paths: ['terragrunt/**']
  workflow_dispatch:
    inputs:
      target_component:
        description: 'Component to deploy (bootstrap, shared-services, dev, staging, production, or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - bootstrap
          - shared-services
          - dev
          - staging
          - production

env:
  AWS_REGION: eu-central-1
  TF_VERSION: 1.13.5
  TERRAGRUNT_VERSION: 0.67.16

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Plan (${{ matrix.component }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: 
          - bootstrap
          - shared-services
          - dev-vpc
          - dev-eks  
          - dev-rds
          - staging-vpc
          - staging-eks
          - staging-rds
          - production-vpc
          - production-eks
          - production-rds
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Component Path
        id: component
        run: |
          case "${{ matrix.component }}" in
            bootstrap) echo "path=bootstrap" >> $GITHUB_OUTPUT ;;
            shared-services) echo "path=shared-services" >> $GITHUB_OUTPUT ;;
            dev-vpc) echo "path=environments/dev/vpc" >> $GITHUB_OUTPUT ;;
            dev-eks) echo "path=environments/dev/eks" >> $GITHUB_OUTPUT ;;
            dev-rds) echo "path=environments/dev/rds" >> $GITHUB_OUTPUT ;;
            staging-vpc) echo "path=environments/staging/vpc" >> $GITHUB_OUTPUT ;;
            staging-eks) echo "path=environments/staging/eks" >> $GITHUB_OUTPUT ;;
            staging-rds) echo "path=environments/staging/rds" >> $GITHUB_OUTPUT ;;
            production-vpc) echo "path=environments/production/vpc" >> $GITHUB_OUTPUT ;;
            production-eks) echo "path=environments/production/eks" >> $GITHUB_OUTPUT ;;
            production-rds) echo "path=environments/production/rds" >> $GITHUB_OUTPUT ;;
          esac

      - name: Terragrunt Plan
        working-directory: terragrunt
        run: |
          terragrunt plan --terragrunt-working-dir ${{ steps.component.outputs.path }}

  apply:
    name: Apply (${{ matrix.component }})
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        include:
          # Sequential deployment with dependencies
          - component: bootstrap
            depends_on: []
          - component: shared-services  
            depends_on: [bootstrap]
          - component: dev-vpc
            depends_on: [bootstrap]
          - component: dev-eks
            depends_on: [dev-vpc]
          - component: dev-rds
            depends_on: [dev-eks]
          - component: staging-vpc
            depends_on: [bootstrap]
          - component: staging-eks
            depends_on: [staging-vpc]
          - component: staging-rds
            depends_on: [staging-eks]
          - component: production-vpc
            depends_on: [bootstrap]
          - component: production-eks
            depends_on: [production-vpc]
          - component: production-rds
            depends_on: [production-eks]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Component Path
        id: component
        run: |
          case "${{ matrix.component }}" in
            bootstrap) echo "path=bootstrap" >> $GITHUB_OUTPUT ;;
            shared-services) echo "path=shared-services" >> $GITHUB_OUTPUT ;;
            dev-vpc) echo "path=environments/dev/vpc" >> $GITHUB_OUTPUT ;;
            dev-eks) echo "path=environments/dev/eks" >> $GITHUB_OUTPUT ;;
            dev-rds) echo "path=environments/dev/rds" >> $GITHUB_OUTPUT ;;
            staging-vpc) echo "path=environments/staging/vpc" >> $GITHUB_OUTPUT ;;
            staging-eks) echo "path=environments/staging/eks" >> $GITHUB_OUTPUT ;;
            staging-rds) echo "path=environments/staging/rds" >> $GITHUB_OUTPUT ;;
            production-vpc) echo "path=environments/production/vpc" >> $GITHUB_OUTPUT ;;
            production-eks) echo "path=environments/production/eks" >> $GITHUB_OUTPUT ;;
            production-rds) echo "path=environments/production/rds" >> $GITHUB_OUTPUT ;;
          esac

      - name: Terragrunt Apply
        working-directory: terragrunt
        run: |
          terragrunt apply --terragrunt-working-dir ${{ steps.component.outputs.path }} --terragrunt-non-interactive
